/*
 * fontgen.c — host-side tool: rasterizes a TrueType font with FreeType
 * and emits a C header with packed antialiased glyphs for the Viteza OS
 * kernel renderer.
 *
 * Build:  cc -o tools/fontgen tools/fontgen.c $(pkg-config --cflags --libs freetype2)
 * Run:    ./tools/fontgen <font.ttf> ui/renderer/font_baked.h
 *
 * The generated header contains, for the ASCII range 32..126, the glyphs
 * baked at two pixel sizes (regular and large) in a packed alpha format.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ft2build.h>
#include FT_FREETYPE_H

#define CH_START 32
#define CH_END   126
#define FONT_CHAR_COUNT_LOCAL(m) (CH_END - CH_START + 1)

typedef struct {
    long  offset;      /* byte offset into the packed alpha array */
    unsigned char adv; /* advance width in pixels */
    unsigned char w;   /* bitmap width in pixels */
    unsigned char h;   /* bitmap height in pixels */
    signed char   top; /* rows above the baseline (bitmap_top) */
} glyph_meta;

static unsigned char *alpha_pool = NULL;
static long alpha_pool_size = 0;
static long alpha_pool_cap = 0;

static void pool_push(const unsigned char *data, long n)
{
    if (alpha_pool_size + n > alpha_pool_cap) {
        alpha_pool_cap = (alpha_pool_cap + n) * 2 + 4096;
        alpha_pool = realloc(alpha_pool, (size_t)alpha_pool_cap);
        if (!alpha_pool) { fprintf(stderr, "out of memory\n"); exit(1); }
    }
    memcpy(alpha_pool + alpha_pool_size, data, (size_t)n);
    alpha_pool_size += n;
}

static int bake_size(FT_Face face, int pixel_size, glyph_meta *meta, int *line_h,
                     int *ascent, int *descent)
{
    FT_Error err = FT_Set_Pixel_Sizes(face, 0, pixel_size);
    if (err) { fprintf(stderr, "FT_Set_Pixel_Sizes(%d) failed\n", pixel_size); return -1; }

    *line_h  = face->size->metrics.height >> 6;
    *ascent  = face->size->metrics.ascender >> 6;
    *descent = face->size->metrics.descender >> 6;

    for (int ch = CH_START; ch <= CH_END; ch++) {
        err = FT_Load_Char(face, ch, FT_LOAD_RENDER);
        if (err) { fprintf(stderr, "FT_Load_Char(%d) failed\n", ch); return -1; }

        FT_Bitmap *bm = &face->glyph->bitmap;
        glyph_meta *m = &meta[ch - CH_START];

        m->offset = alpha_pool_size;
        m->adv = (unsigned char)((face->glyph->advance.x + 32) >> 6);
        m->w   = (unsigned char)bm->width;
        m->h   = (unsigned char)bm->rows;
        m->top = (signed char)face->glyph->bitmap_top;

        /* copy rows, stripping padding to tightly pack w*h bytes */
        for (unsigned int r = 0; r < bm->rows; r++) {
            const unsigned char *src = bm->buffer + (long)r * bm->pitch;
            pool_push(src, (long)bm->width);
        }
    }
    return 0;
}

static void emit_header(const char *path, glyph_meta *reg, glyph_meta *lg,
                        int line_h_reg, int ascent_reg, int descent_reg,
                        int line_h_lg, int ascent_lg, int descent_lg)
{
    FILE *f = fopen(path, "w");
    if (!f) { perror(path); exit(1); }

    fprintf(f, "/* Generated by tools/fontgen.c — DO NOT EDIT. */\n");
    fprintf(f, "#ifndef FONT_BAKED_H\n#define FONT_BAKED_H\n\n");
    fprintf(f, "#define FONT_CHARSET_START %d\n", CH_START);
    fprintf(f, "#define FONT_CHARSET_END   %d\n", CH_END);
    fprintf(f, "#define FONT_CHAR_COUNT    %d\n", CH_END - CH_START + 1);
    fprintf(f, "#define FONT_LINE_H_REG    %d\n", line_h_reg);
    fprintf(f, "#define FONT_ASCENT_REG    %d\n", ascent_reg);
    fprintf(f, "#define FONT_DESCENT_REG   %d\n", descent_reg);
    fprintf(f, "#define FONT_LINE_H_LG     %d\n", line_h_lg);
    fprintf(f, "#define FONT_ASCENT_LG     %d\n", ascent_lg);
    fprintf(f, "#define FONT_DESCENT_LG    %d\n", descent_lg);
    fprintf(f, "\n");

    fprintf(f, "typedef struct {\n"
               "    unsigned int offset;\n"
               "    unsigned char adv, w, h;\n"
               "    signed char top;\n"
               "} baked_glyph_t;\n\n");

    /* regular glyphs */
    fprintf(f, "static const baked_glyph_t font_reg[FONT_CHAR_COUNT] = {\n");
    for (int i = 0; i < FONT_CHAR_COUNT_LOCAL(reg); i++) {
        fprintf(f, "    {%6u,%3d,%3d,%3d,%4d},%s\n",
                (unsigned)reg[i].offset, reg[i].adv, reg[i].w, reg[i].h, reg[i].top,
                (i % 4 == 3) ? "\n" : "");
    }
    fprintf(f, "};\n\n");

    /* large glyphs */
    fprintf(f, "static const baked_glyph_t font_lg[FONT_CHAR_COUNT] = {\n");
    for (int i = 0; i < FONT_CHAR_COUNT_LOCAL(lg); i++) {
        fprintf(f, "    {%6u,%3d,%3d,%3d,%4d},%s\n",
                (unsigned)lg[i].offset, lg[i].adv, lg[i].w, lg[i].h, lg[i].top,
                (i % 4 == 3) ? "\n" : "");
    }
    fprintf(f, "};\n\n");

    /* packed alpha bytes */
    fprintf(f, "static const unsigned char font_alpha[%ld] = {\n", alpha_pool_size);
    for (long i = 0; i < alpha_pool_size; i++) {
        fprintf(f, "%3d,", alpha_pool[i]);
        if (i % 20 == 19) fprintf(f, "\n");
    }
    if (alpha_pool_size % 20 != 0) fprintf(f, "\n");
    fprintf(f, "};\n\n#endif\n");

    fclose(f);
}

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <font.ttf> <out.h>\n", argv[0]);
        return 1;
    }

    FT_Library lib;
    FT_Face face;
    if (FT_Init_FreeType(&lib)) { fprintf(stderr, "FT_Init_FreeType failed\n"); return 1; }
    if (FT_New_Face(lib, argv[1], 0, &face)) { fprintf(stderr, "cannot open font %s\n", argv[1]); return 1; }

    int n = CH_END - CH_START + 1;
    glyph_meta *reg = calloc((size_t)n, sizeof(glyph_meta));
    glyph_meta *lg  = calloc((size_t)n, sizeof(glyph_meta));
    if (!reg || !lg) { fprintf(stderr, "out of memory\n"); return 1; }

    int lh_r, as_r, de_r, lh_l, as_l, de_l;
    if (bake_size(face, 16, reg, &lh_r, &as_r, &de_r)) return 1;
    long reg_bytes = alpha_pool_size;
    if (bake_size(face, 32, lg, &lh_l, &as_l, &de_l)) return 1;
    long lg_bytes = alpha_pool_size - reg_bytes;

    fprintf(stderr, "regular: %ld glyph bytes, line_h=%d asc=%d desc=%d\n",
            reg_bytes, lh_r, as_r, de_r);
    fprintf(stderr, "large:   %ld glyph bytes, line_h=%d asc=%d desc=%d\n",
            lg_bytes, lh_l, as_l, de_l);
    fprintf(stderr, "total:   %ld bytes\n", alpha_pool_size);

    emit_header(argv[2], reg, lg, lh_r, as_r, de_r, lh_l, as_l, de_l);

    FT_Done_Face(face);
    FT_Done_FreeType(lib);
    return 0;
}
