#!/usr/bin/env python3
"""Genera kernel/drivers/audio/stt_data.h con tutti i dati precalcolati per il motore C."""
import os
import sys
import json

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
import stt_engine as E

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                   "kernel", "drivers", "audio", "stt_data.h")

FFT_SIZE = E.FFT_SIZE
N_MELS = E.N_MELS
N_MFCC = E.N_MFCC
N_FEAT = N_MFCC * 3
T_FRAMES = 32
SCALE = 256.0
N_WIN = int(E.SAMPLE_RATE * E.FRAME_MS / 1000)

# mel filterbank (n_mels, n_fft//2+1)
fbank = E.mel_filterbank(N_MELS, FFT_SIZE, E.SAMPLE_RATE)
assert fbank.shape == (N_MELS, FFT_SIZE // 2 + 1)

# DCT-II matrix (first N_MFCC coeffs, rows k, cols m), scale folded in
n = N_MELS
m = np.arange(n)[None, :]
k = np.arange(n)[:, None]
basis = np.cos(np.pi / n * (m + 0.5) * k)
basis[0] *= 1.0 / np.sqrt(2.0)
dctmat = basis[:N_MFCC] * np.sqrt(2.0 / n)

# hamming window (np.hamming uses N-1 denominator)
hamm = 0.54 - 0.46 * np.cos(2.0 * np.pi * np.arange(N_WIN) / (N_WIN - 1))

# fft trig tables
idx = np.arange(FFT_SIZE)
cos_tab = np.cos(2.0 * np.pi * idx / FFT_SIZE)
sin_tab = np.sin(2.0 * np.pi * idx / FFT_SIZE)

# templates -> resample to T_FRAMES x N_FEAT, quantize int16 (scale 256)
vocab = json.load(open(E.VOCAB_FILE))
phrases = list(vocab.keys())
tpl_arrays = []  # [phrase][template] -> int16 array T_FRAMES*N_FEAT
for phrase in phrases:
    per = []
    for rel in vocab[phrase]:
        feats = np.load(os.path.join(E.TEMPLATE_DIR, rel))
        f32 = E._len_norm(feats, T_FRAMES)
        q = np.clip(np.round(f32 * SCALE), -32768, 32767).astype(np.int16)
        per.append(q)
    tpl_arrays.append(per)


def cfloat(v):
    s = repr(float(v))
    return s + "f"


def fmt_floats(arr):
    return ", ".join(cfloat(float(v)) for v in arr.ravel())


def fmt_ints(arr):
    return ", ".join(str(int(v)) for v in arr.ravel())


with open(OUT, "w") as f:
    f.write("// Auto-generated by tools/gen_stt_data.py — NON MODIFICARE.\n")
    f.write("#ifndef STT_DATA_H\n#define STT_DATA_H\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define STT_NPHRASE {len(phrases)}\n")
    f.write(f"#define STT_NTPL {len(tpl_arrays[0])}\n")
    f.write(f"#define STT_TFRAMES {T_FRAMES}\n")
    f.write(f"#define STT_NFEAT {N_FEAT}\n")
    f.write(f"#define STT_TSCALE {cfloat(SCALE)}\n")
    f.write(f"#define STT_MELS {N_MELS}\n")
    f.write(f"#define STT_NFFT {FFT_SIZE}\n")
    f.write(f"#define STT_MELBINS {FFT_SIZE // 2 + 1}\n")
    f.write(f"#define STT_NWIN {N_WIN}\n")
    f.write(f"#define STT_HOP {int(E.SAMPLE_RATE * E.HOP_MS / 1000)}\n")
    f.write(f"#define STT_NCOEF {N_MFCC}\n\n")

    f.write(f"static const char *const stt_phrases[{len(phrases)}] = {{\n")
    for p in phrases:
        f.write(f'    "{p}",\n')
    f.write("};\n\n")

    f.write(f"static const int16_t stt_templates[{len(phrases)}][{len(tpl_arrays[0])}][{T_FRAMES * N_FEAT}] = {{\n")
    for pi, per in enumerate(tpl_arrays):
        f.write(f"    {{ // '{phrases[pi]}'\n")
        for t in per:
            f.write("        {")
            f.write(fmt_ints(t))
            f.write("},\n")
        f.write("    },\n")
    f.write("};\n\n")

    f.write(f"static const float stt_mel_bank[{N_MELS}][{FFT_SIZE // 2 + 1}] = {{\n")
    for row in fbank:
        f.write("    {" + fmt_floats(row) + "},\n")
    f.write("};\n\n")

    f.write(f"static const float stt_dct_mat[{N_MFCC}][{N_MELS}] = {{\n")
    for row in dctmat:
        f.write("    {" + fmt_floats(row) + "},\n")
    f.write("};\n\n")

    f.write(f"static const float stt_hamming[{N_WIN}] = {{ " + fmt_floats(hamm) + " };\n\n")
    f.write(f"static const float stt_cos_tab[{FFT_SIZE}] = {{ " + fmt_floats(cos_tab) + " };\n\n")
    f.write(f"static const float stt_sin_tab[{FFT_SIZE}] = {{ " + fmt_floats(sin_tab) + " };\n\n")
    f.write("#endif\n")

print("scritto", OUT, os.path.getsize(OUT), "bytes")
